### ISSUE TITLE
Lizezen statt Lizenzen

### ISSUE THREAD

**Issue by berio23** [blitzdose/DualisNotifier#1]
Nur ein kleiner Rechtschreibfehler hier, Danke für die App ist echt sehr Hilfreich ! 
![Screenshot_20210918-201850_DHBW Dualis Notifier](https://user-images.githubusercontent.com/23236606/133898585-00a6809b-fe77-4f97-a70b-1db29444d76d.jpg)

**Comment by blitzdose** [comment]
Fehler ist behoben. Die neue Version ist nach der Überprüfung durch Google Play verfügbar. Dante für die Info!
